### ISSUE TITLE
Anyone using this with digitalocean spaces?

### ISSUE THREAD

**Issue by jyoost** [superflows-dev/react-upload-to-s3#4]
if so, can you share changes needed

**Comment by superflows-dev** [comment]
No, at the moment, it supports on AWS S3.

**Comment by jyoost** [comment]
Thanks,  I am using with aws now.

**Comment by superflows-dev** [comment]
Feel free to ask for help. You can also ping me on the discord server for faster replies: https://discord.gg/ksEXS4P9h6
